[workspace]
members = ["cli", "sena"]
resolver = '2'

[workspace.package]
name = "lucky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]

# internal libraries
sena = { path = "sena" }
